# Generated by Django 4.1.1 on 2022-09-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='slug',
        ),
    ]
