# Generated by Django 4.1.1 on 2022-09-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0002_remove_lugar_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='author',
            new_name='autor',
        ),
    ]
