# Generated by Django 4.1.1 on 2022-09-23 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0006_like_like_unique_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='lugar.lugar'),
        ),
    ]
