# Generated by Django 4.1.1 on 2022-09-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0006_remove_avaliacao_data_hora_alter_avaliacao_avaliacao'),
        ('lugar', '0007_alter_like_lugar'),
    ]

    operations = [
    ]
