# Generated by Django 4.1.1 on 2022-10-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0009_comentario_delete_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='texto',
        ),
    ]
