# Generated by Django 4.1.1 on 2022-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0010_rename_comentario_comentario_texto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='autor',
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('autor_id', 'lugar_id'), name='unique_user'),
        ),
    ]
