# Generated by Django 4.1.1 on 2022-11-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0010_rename_comentario_comentario_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='alt_text',
            field=models.TextField(blank=True),
        ),
    ]
