# Generated by Django 4.1.1 on 2022-11-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0011_lugar_alt_text'),
        ('lugar', '0011_remove_like_unique_user_rename_user_like_autor_and_more'),
    ]

    operations = [
    ]
