# Generated by Django 4.1.1 on 2022-11-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0012_merge_20221105_1721'),
        ('lugar', '0012_merge_20221105_1804'),
        ('lugar', '0012_merge_20221105_1821'),
    ]

    operations = [
    ]
